### PR TITLE
handle 303

### PR DESCRIPTION
**Pull request by j4qfrost**
I think there's a better way to handle this, but I can't think of one right now.

### CODE REVIEW

**Comment by rousan** [comment]
Hey @j4qfrost, thanks for the PR. Let me check it once.

**Comment by rousan** [comment]
@j4qfrost, it's working, but can you please send the same PR to my develop branch instead of master, as we follow develop as the development branch?

**Comment by j4qfrost** [comment]
Done.

**Comment by rousan** [comment]
Hey @j4qfrost,
Thanks for the fix.
Published a release `v1.1.0` with the fix. Check it out:
```sh
npm rm -g linkedin-auto-connect
npm i -g linkedin-auto-connect
```

**Pull request merged**
